package tech.ada.projeto_ada.exception;

public enum ErroCodigo {
    USUARIO_NAO_ENCONTRADO,
    CAMPO_INVALIDO,
    DATA_INVALIDA,
    EMAIL_DUPLICADO,
    REQUISICAO_INVALIDA,
    VEICULO_INDISPONIVEL,
    CLIENTE_NAO_ENCONTRADO,
    TELEFONE_DUPLICADO,
    VEICULO_NAO_ENCONTRADO,
    PLACA_DUPLICADA,
}
