package tech.ada.projeto_ada.exception;

public enum ErroCodigo {
    CAMPO_INVALIDO,
    DATA_INVALIDA,
    REQUISICAO_INVALIDA,
    VEICULO_INDISPONIVEL,
    EMAIL_DUPLICADO,
    TELEFONE_DUPLICADO,
    PLACA_DUPLICADA,
    USUARIO_NAO_ENCONTRADO,
    CLIENTE_NAO_ENCONTRADO,
    VEICULO_NAO_ENCONTRADO,
    LOCACAO_NAO_ENCONTRADA,

}
