spring.application.name=projeto_ada_test

server.port=8081

#Configurações Banco de Dados
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:test2
spring.datasource.username=sa2
spring.datasource.password=
spring.sql.init.mode=always
spring.h2.console.settings.web-allow-others=true

#Configurações H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

#Configurações JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# Configurações do Swagger
springdoc.swagger-ui.path=/swagger.html
springdoc.api-docs.path=/v3/api-docs

# Configurações do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Simular outros comportamentos além de GET e POST
spring.mvc.hiddenmethod.filter.enabled=true

# Desativa segurança para facilitar testes de controller com HTML (sem CSRF)
spring.main.allow-bean-definition-overriding=true